# Functions

Максимальный code coverage 92.9% так как есть 2 места, где кидаются исключения и у них есть ветки:
 - исключение поймано
 - исключение не поймано

У нас нет возможности протестировать не пойманное исключение, так как тогда программа завершиться.

# Tree

Невозможно проверить ветки:
 - Исключения в 13 и 17 строке (2 ветки)
 - 12 строка. Нельзя проверить ветки так как нужно получить system_error,
   а файловую систему ломать не хочется. Где тут еще одна ветка теряется -- 
   не понятно, а я весь boost прошел(2 ветки)
 - 16 строка. 2 ветки теряются в boost, хотя там один if судя по библиотеке
 - 19 строка. Нельзя получить другие ветки так как путь уже проверен и нельзя получить 0 в filename (3)
 - 21 - не понятные ветки из boost (5)
 - 23, 30 - возможно, что закончится память, но как это тестить неясно (3)
 - 24, 31 - ветки с исключениями, которые не возможны из-за уже существующих проверок (3)
 - 48 - честно говоря не вижу, где тут может быть 6 веток (3)

Максимально возможный branch coverage - (72 - 23)/72 ~ 68.1%

# Weather

Невозможно проверить ветки:
 - 14 - throw(1 ветка)
 - 28 - нужно изменять библиотеку отправки запросов(4)
 - очень много веток появляется из-за std::string. Думаю это связано с невозможностью выделить память, 
   что очень сложно проверять (28)
 - Несколько веток находятся в json библиотеке (4)

Максимально возможный branch coverage - (108 - 37)/108 ~ 65.7%
